kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: odp-api  
  labels:
    app: odp-api 
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: odp-api
    deploymentconfig: odp-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: odp-api
        deploymentconfig: odp-api
    spec:
      containers:
        - name: odp-api
          image: 'image-registry.openshift-image-registry.svc:5000/prod/odp-api:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: APPINSIGHTS_CONNECTIONSTRING
              value: >-
                InstrumentationKey=776e0b77-9e47-475e-b00f-2b578270aaee;IngestionEndpoint=https://francecentral-0.in.applicationinsights.azure.com/
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HOSTINGSTARTUPASSEMBLIES
              value: APB.ARQ.APIBASE
            - name: ASPNETCORE_URLS
              value: 'http://+:8080'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
 